mod noto_sans_mono_cjk_sc_regular_24;
mod noto_sans_mono_cjk_sc_regular_36;

pub use noto_sans_mono_cjk_sc_regular_24::FONT as NOTO_SANS_MONO_CJK_SC_REGULAR_24;
pub use noto_sans_mono_cjk_sc_regular_36::FONT as NOTO_SANS_MONO_CJK_SC_REGULAR_36;
